### ISSUE TITLE
Todo first release

### ISSUE THREAD

**Issue by petermein** [rapideinternet/laravel-queue-kafka#1]
- [x] Implement size to reflect the remaining item on the topic
- [x] Check the release function
- [x] Fix README to reflect actual data
- [x] Implement unit tests
- [x] Setup Travis

**Comment by rapideinternet** [comment]
Size function is not viable in Kafka since its a virtually endless stream of messages
